name: Build

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          #tries to use node version from .nvmrc or .node-version file from root. use 14.x if neither exists.
          node-version-file: '.nvmrc'
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install